/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoparqueo;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Elyic
 */
public class MDI extends javax.swing.JFrame {

    /**
     * Creates new form MDI
     */
    Parqueo parqueo = new Parqueo();
    int[] status = new int[15];
    public MDI() {
        initComponents();
        this.setLocationRelativeTo(null);
        CargarEstado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        Carro1 = new javax.swing.JLabel();
        Carro2 = new javax.swing.JLabel();
        Carro3 = new javax.swing.JLabel();
        Carro4 = new javax.swing.JLabel();
        Carro5 = new javax.swing.JLabel();
        Carro6 = new javax.swing.JLabel();
        Carro7 = new javax.swing.JLabel();
        Carro8 = new javax.swing.JLabel();
        Carro9 = new javax.swing.JLabel();
        Carro10 = new javax.swing.JLabel();
        Carro11 = new javax.swing.JLabel();
        Carro12 = new javax.swing.JLabel();
        Carro13 = new javax.swing.JLabel();
        Carro14 = new javax.swing.JLabel();
        Carro15 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        MenuPrincipal = new javax.swing.JMenuBar();
        Inicio = new javax.swing.JMenu();
        Salir = new javax.swing.JMenu();
        ControlParqueo = new javax.swing.JMenu();
        IngresoParqueo = new javax.swing.JMenu();
        CobrarParqueo = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        miIngresoCliente = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        Info = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(913, 702));
        setResizable(false);

        jDesktopPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jDesktopPane1MouseEntered(evt);
            }
        });

        Carro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carro1MouseClicked(evt);
            }
        });
        jDesktopPane1.add(Carro1);
        Carro1.setBounds(0, 10, 100, 200);

        Carro2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carro2MouseClicked(evt);
            }
        });
        jDesktopPane1.add(Carro2);
        Carro2.setBounds(100, 10, 100, 200);

        Carro3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carro3MouseClicked(evt);
            }
        });
        jDesktopPane1.add(Carro3);
        Carro3.setBounds(200, 10, 100, 200);

        Carro4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carro4MouseClicked(evt);
            }
        });
        jDesktopPane1.add(Carro4);
        Carro4.setBounds(310, 10, 90, 200);

        Carro5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carro5MouseClicked(evt);
            }
        });
        jDesktopPane1.add(Carro5);
        Carro5.setBounds(410, 10, 90, 200);

        Carro6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carro6MouseClicked(evt);
            }
        });
        jDesktopPane1.add(Carro6);
        Carro6.setBounds(510, 10, 100, 200);

        Carro7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carro7MouseClicked(evt);
            }
        });
        jDesktopPane1.add(Carro7);
        Carro7.setBounds(600, 10, 100, 200);

        Carro8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carro8MouseClicked(evt);
            }
        });
        jDesktopPane1.add(Carro8);
        Carro8.setBounds(700, 10, 100, 200);

        Carro9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carro9MouseClicked(evt);
            }
        });
        jDesktopPane1.add(Carro9);
        Carro9.setBounds(800, 10, 100, 200);

        Carro10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carro10MouseClicked(evt);
            }
        });
        jDesktopPane1.add(Carro10);
        Carro10.setBounds(700, 340, 200, 100);

        Carro11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carro11MouseClicked(evt);
            }
        });
        jDesktopPane1.add(Carro11);
        Carro11.setBounds(700, 440, 200, 100);

        Carro12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carro12MouseClicked(evt);
            }
        });
        jDesktopPane1.add(Carro12);
        Carro12.setBounds(700, 540, 200, 100);

        Carro13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carro13MouseClicked(evt);
            }
        });
        jDesktopPane1.add(Carro13);
        Carro13.setBounds(10, 540, 200, 100);

        Carro14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carro14MouseClicked(evt);
            }
        });
        jDesktopPane1.add(Carro14);
        Carro14.setBounds(10, 440, 200, 100);

        Carro15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carro15MouseClicked(evt);
            }
        });
        jDesktopPane1.add(Carro15);
        Carro15.setBounds(10, 340, 200, 100);

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fond-iloveimg-resized.png"))); // NOI18N
        jDesktopPane1.add(Fondo);
        Fondo.setBounds(0, 0, 920, 660);

        Inicio.setText("Inicio");
        Inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InicioMouseClicked(evt);
            }
        });

        Salir.setText("Salir");
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
        });
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        Inicio.add(Salir);

        MenuPrincipal.add(Inicio);

        ControlParqueo.setText("Parqueo");
        ControlParqueo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ControlParqueoMouseClicked(evt);
            }
        });

        IngresoParqueo.setText("Ingreso");
        IngresoParqueo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IngresoParqueoMouseClicked(evt);
            }
        });
        ControlParqueo.add(IngresoParqueo);

        CobrarParqueo.setText("Cobrar");
        CobrarParqueo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CobrarParqueoActionPerformed(evt);
            }
        });
        ControlParqueo.add(CobrarParqueo);

        MenuPrincipal.add(ControlParqueo);

        jMenu1.setText("Clientes");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        miIngresoCliente.setText("Ingreso Cliente");
        miIngresoCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miIngresoClienteMouseClicked(evt);
            }
        });
        miIngresoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miIngresoClienteActionPerformed(evt);
            }
        });
        jMenu1.add(miIngresoCliente);

        jMenuItem1.setText("Editar Cliente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        MenuPrincipal.add(jMenu1);

        jMenu2.setText("Vehiculos");

        jMenuItem2.setText("Ingreso de Vehiculo");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Editar Vehiculo");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        MenuPrincipal.add(jMenu2);

        jMenu3.setText("Reportes");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem4.setText("Por Fecha");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem6.setText("Entre Fechas");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem5.setText("Cierre de Caja");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        MenuPrincipal.add(jMenu3);

        jMenu4.setText("Acerca de");

        Info.setText("Info");
        Info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoActionPerformed(evt);
            }
        });
        jMenu4.add(Info);

        MenuPrincipal.add(jMenu4);

        setJMenuBar(MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 921, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirActionPerformed

    private void InicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InicioMouseClicked
                            
    }//GEN-LAST:event_InicioMouseClicked

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
         System.exit(0);
    }//GEN-LAST:event_SalirMouseClicked

    private void ControlParqueoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ControlParqueoMouseClicked
        
    }//GEN-LAST:event_ControlParqueoMouseClicked

    private void IngresoParqueoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresoParqueoMouseClicked
        // Se crea el objeto        
        jfiIngresoParqueo ingresoparqueo = new jfiIngresoParqueo(0);
        // se añade al jDesktopPane
        jDesktopPane1.add(ingresoparqueo);
        //se muestra en pantalla
        ingresoparqueo.show();
    }//GEN-LAST:event_IngresoParqueoMouseClicked
    public void CargarEstado(){
        parqueo.EstadoTablaParqueo(status);
        for (int i = 0; i < status.length; i++) {
            switch ((i+1)){
                case 1:
                    if (status[i]==1) {
                Parqueo parqueo = new Parqueo();
                Factura factura = new Factura();
                parqueo.ConsultaTablaParqueo(1);
                factura.ConsultaTablaFactura(parqueo.ID_Factura);
                Carro1.setToolTipText("Cliente: "+factura.ClienteNombre+" "+factura.ClienteApellido);
                Carro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/autopng.png")));
                    }else{
                 Carro1.setIcon(null);
                 Carro1.setToolTipText("Libre!");
                    }
                break;
                case 2:
                     if (status[i]==1) {
                Parqueo parqueo = new Parqueo();
                Factura factura = new Factura();
                parqueo.ConsultaTablaParqueo(2);
                factura.ConsultaTablaFactura(parqueo.ID_Factura);
                Carro2.setToolTipText("Cliente: "+factura.ClienteNombre+" "+factura.ClienteApellido);
                Carro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/autopng.png")));
                    }else{
                 Carro2.setIcon(null);
                 Carro2.setToolTipText("Libre!");
                    }
                break;
                case 3:
                    if (status[i]==1) {
                Parqueo parqueo = new Parqueo();
                Factura factura = new Factura();
                parqueo.ConsultaTablaParqueo(3);
                factura.ConsultaTablaFactura(parqueo.ID_Factura);
                Carro3.setToolTipText("Cliente: "+factura.ClienteNombre+" "+factura.ClienteApellido);
                Carro3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/autopng.png")));
                    }else{
                 Carro3.setIcon(null);
                 Carro3.setToolTipText("Libre!");
                    }
                break;
                case 4:
                    if (status[i]==1) {
                Parqueo parqueo = new Parqueo();
                Factura factura = new Factura();
                parqueo.ConsultaTablaParqueo(4);
                factura.ConsultaTablaFactura(parqueo.ID_Factura);
                Carro4.setToolTipText("Cliente: "+factura.ClienteNombre+" "+factura.ClienteApellido);
                Carro4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/autopng.png")));
                    }else{
                 Carro4.setIcon(null);
                 Carro4.setToolTipText("Libre!");
                    }
                break;
                case 5:
                    if (status[i]==1) {
                Parqueo parqueo = new Parqueo();
                Factura factura = new Factura();
                parqueo.ConsultaTablaParqueo(5);
                factura.ConsultaTablaFactura(parqueo.ID_Factura);
                Carro5.setToolTipText("Cliente: "+factura.ClienteNombre+" "+factura.ClienteApellido);
                Carro5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/autopng.png")));
                    }else{
                 Carro5.setIcon(null);
                 Carro5.setToolTipText("Libre!");
                    }
                break;
                case 6:
                    if (status[i]==1) {
                 Parqueo parqueo = new Parqueo();
                Factura factura = new Factura();
                parqueo.ConsultaTablaParqueo(6);
                factura.ConsultaTablaFactura(parqueo.ID_Factura);
                Carro6.setToolTipText("Cliente: "+factura.ClienteNombre+" "+factura.ClienteApellido);
                Carro6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/autopng.png")));
                    }else{
                 Carro6.setIcon(null);
                 Carro6.setToolTipText("Libre!");
                    }
                break;
                case 7:
                    if (status[i]==1) {
               Parqueo parqueo = new Parqueo();
                Factura factura = new Factura();
                parqueo.ConsultaTablaParqueo(7);
                factura.ConsultaTablaFactura(parqueo.ID_Factura);
                Carro7.setToolTipText("Cliente: "+factura.ClienteNombre+" "+factura.ClienteApellido);
                Carro7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/autopng.png")));
                    }else{
                 Carro7.setIcon(null);
                 Carro7.setToolTipText("Libre!");
                    }
                break;
                case 8:
                    if (status[i]==1) {
                Parqueo parqueo = new Parqueo();
                Factura factura = new Factura();
                parqueo.ConsultaTablaParqueo(8);
                factura.ConsultaTablaFactura(parqueo.ID_Factura);
                Carro8.setToolTipText("Cliente: "+factura.ClienteNombre+" "+factura.ClienteApellido);
                Carro8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/autopng.png")));
                    }else{
                 Carro8.setIcon(null);
                 Carro8.setToolTipText("Libre!");
                    }
                break;
                case 9:
                    if (status[i]==1) {
                Parqueo parqueo = new Parqueo();
                Factura factura = new Factura();
                parqueo.ConsultaTablaParqueo(9);
                factura.ConsultaTablaFactura(parqueo.ID_Factura);
                Carro9.setToolTipText("Cliente: "+factura.ClienteNombre+" "+factura.ClienteApellido);
                Carro9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/autopng.png")));
                    }else{
                 Carro9.setIcon(null);
                 Carro9.setToolTipText("Libre!");
                    }
                break;
                case 10:
                    if (status[i]==1) {
                Parqueo parqueo = new Parqueo();
                Factura factura = new Factura();
                parqueo.ConsultaTablaParqueo(10);
                factura.ConsultaTablaFactura(parqueo.ID_Factura);
                Carro10.setToolTipText("Cliente: "+factura.ClienteNombre+" "+factura.ClienteApellido);
                Carro10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/autopngh.png")));
                    }else{
                 Carro10.setIcon(null);
                 Carro10.setToolTipText("Libre!");
                    }
                break;
                case 11:
                    if (status[i]==1) {
                Parqueo parqueo = new Parqueo();
                Factura factura = new Factura();
                parqueo.ConsultaTablaParqueo(11);
                factura.ConsultaTablaFactura(parqueo.ID_Factura);
                Carro11.setToolTipText("Cliente: "+factura.ClienteNombre+" "+factura.ClienteApellido);
                Carro11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/autopngh.png")));
                    }else{
                 Carro11.setIcon(null);
                 Carro11.setToolTipText("Libre!");
                    }
                break;
                case 12:
                    if (status[i]==1) {
                Parqueo parqueo = new Parqueo();
                Factura factura = new Factura();
                parqueo.ConsultaTablaParqueo(12);
                factura.ConsultaTablaFactura(parqueo.ID_Factura);
                Carro12.setToolTipText("Cliente: "+factura.ClienteNombre+" "+factura.ClienteApellido);
                Carro12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/autopngh.png")));
                    }else{
                 Carro12.setIcon(null);
                 Carro12.setToolTipText("Libre!");
                    }
                break;
                case 13:
                    if (status[i]==1) {
                Parqueo parqueo = new Parqueo();
                Factura factura = new Factura();
                parqueo.ConsultaTablaParqueo(13);
                factura.ConsultaTablaFactura(parqueo.ID_Factura);
                Carro13.setToolTipText("Cliente: "+factura.ClienteNombre+" "+factura.ClienteApellido);
                Carro13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/autopngh.png")));
                    }else{
                 Carro13.setIcon(null);
                 Carro13.setToolTipText("Libre!");
                    }
                break;
                case 14:
                    if (status[i]==1) {
                Parqueo parqueo = new Parqueo();
                Factura factura = new Factura();
                parqueo.ConsultaTablaParqueo(14);
                factura.ConsultaTablaFactura(parqueo.ID_Factura);
                Carro14.setToolTipText("Cliente: "+factura.ClienteNombre+" "+factura.ClienteApellido);
                Carro14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/autopngh.png")));
                    }else{
                 Carro14.setIcon(null);
                 Carro14.setToolTipText("Libre!");
                    }
                break;
                case 15:
                    if (status[i]==1) {
                Parqueo parqueo = new Parqueo();
                Factura factura = new Factura();
                parqueo.ConsultaTablaParqueo(15);
                factura.ConsultaTablaFactura(parqueo.ID_Factura);
                Carro15.setToolTipText("Cliente: "+factura.ClienteNombre+" "+factura.ClienteApellido);
                Carro15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/autopngh.png")));
                    }else{
                 Carro15.setIcon(null);
                 Carro15.setToolTipText("Libre!");
                    }
                break;
                
            }
        }
        
    }
    private void CobrarParqueoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CobrarParqueoActionPerformed
        // TODO add your handling code here:
        CobrarParqueo cobrarparqueo = new CobrarParqueo(0);
        jDesktopPane1.add(cobrarparqueo);
        cobrarparqueo.show();
    }//GEN-LAST:event_CobrarParqueoActionPerformed

    private void jDesktopPane1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDesktopPane1MouseEntered
        // TODO add your handling code here:
        CargarEstado();
    }//GEN-LAST:event_jDesktopPane1MouseEntered

    private void miIngresoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miIngresoClienteActionPerformed
        // TODO add your handling code here:
        IngresoCliente ingresocliente = new IngresoCliente();
        ingresocliente.setVisible(true);        
    }//GEN-LAST:event_miIngresoClienteActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void miIngresoClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miIngresoClienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_miIngresoClienteMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        EditarCliente editarcliente = new EditarCliente();
        editarcliente.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        IngresoVehiculo ingresovehiculo = new IngresoVehiculo();
        ingresovehiculo.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        EditarVehiculo editarvehiculo = new EditarVehiculo();
        editarvehiculo.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
         ReporteFecha reportefecha = new ReporteFecha();
        reportefecha.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        CierreCaja cierrecaja = new CierreCaja();
        cierrecaja.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void Carro1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carro1MouseClicked
        // TODO add your handling code here:
                if (status[0]==1) {
        CobrarParqueo cobrarparqueo = new CobrarParqueo(1);
        jDesktopPane1.add(cobrarparqueo);
        cobrarparqueo.show();
                }else{
                    jfiIngresoParqueo ingresoparqueo = new jfiIngresoParqueo(1);
        // se añade al jDesktopPane
        jDesktopPane1.add(ingresoparqueo);
        //se muestra en pantalla
        ingresoparqueo.show();
                }
        
    }//GEN-LAST:event_Carro1MouseClicked

    private void Carro2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carro2MouseClicked
        // TODO add your handling code here:
        if (status[1]==1) {
        CobrarParqueo cobrarparqueo = new CobrarParqueo(2);
        jDesktopPane1.add(cobrarparqueo);
        cobrarparqueo.show();
                }else{
                    jfiIngresoParqueo ingresoparqueo = new jfiIngresoParqueo(2);
        // se añade al jDesktopPane
        jDesktopPane1.add(ingresoparqueo);
        //se muestra en pantalla
        ingresoparqueo.show();
                }
    }//GEN-LAST:event_Carro2MouseClicked

    private void Carro3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carro3MouseClicked
        // TODO add your handling code here:
        if (status[2]==1) {
        CobrarParqueo cobrarparqueo = new CobrarParqueo(3);
        jDesktopPane1.add(cobrarparqueo);
        cobrarparqueo.show();
                }else{
                    jfiIngresoParqueo ingresoparqueo = new jfiIngresoParqueo(3);
        // se añade al jDesktopPane
        jDesktopPane1.add(ingresoparqueo);
        //se muestra en pantalla
        ingresoparqueo.show();
                }
    }//GEN-LAST:event_Carro3MouseClicked

    private void Carro4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carro4MouseClicked
        // TODO add your handling code here:
        if (status[3]==1) {
        CobrarParqueo cobrarparqueo = new CobrarParqueo(4);
        jDesktopPane1.add(cobrarparqueo);
        cobrarparqueo.show();
                }else{
                    jfiIngresoParqueo ingresoparqueo = new jfiIngresoParqueo(4);
        // se añade al jDesktopPane
        jDesktopPane1.add(ingresoparqueo);
        //se muestra en pantalla
        ingresoparqueo.show();
                }
    }//GEN-LAST:event_Carro4MouseClicked

    private void Carro5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carro5MouseClicked
        // TODO add your handling code here:
        if (status[4]==1) {
        CobrarParqueo cobrarparqueo = new CobrarParqueo(5);
        jDesktopPane1.add(cobrarparqueo);
        cobrarparqueo.show();
                }else{
                    jfiIngresoParqueo ingresoparqueo = new jfiIngresoParqueo(5);
        // se añade al jDesktopPane
        jDesktopPane1.add(ingresoparqueo);
        //se muestra en pantalla
        ingresoparqueo.show();
                }
    }//GEN-LAST:event_Carro5MouseClicked

    private void Carro6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carro6MouseClicked
        // TODO add your handling code here:
        if (status[5]==1) {
        CobrarParqueo cobrarparqueo = new CobrarParqueo(6);
        jDesktopPane1.add(cobrarparqueo);
        cobrarparqueo.show();
                }else{
                    jfiIngresoParqueo ingresoparqueo = new jfiIngresoParqueo(6);
        // se añade al jDesktopPane
        jDesktopPane1.add(ingresoparqueo);
        //se muestra en pantalla
        ingresoparqueo.show();
                }
    }//GEN-LAST:event_Carro6MouseClicked

    private void Carro7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carro7MouseClicked
        // TODO add your handling code here:
        if (status[6]==1) {
        CobrarParqueo cobrarparqueo = new CobrarParqueo(7);
        jDesktopPane1.add(cobrarparqueo);
        cobrarparqueo.show();
                }else{
                    jfiIngresoParqueo ingresoparqueo = new jfiIngresoParqueo(7);
        // se añade al jDesktopPane
        jDesktopPane1.add(ingresoparqueo);
        //se muestra en pantalla
        ingresoparqueo.show();
                }
    }//GEN-LAST:event_Carro7MouseClicked

    private void Carro8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carro8MouseClicked
        // TODO add your handling code here:
        if (status[7]==1) {
        CobrarParqueo cobrarparqueo = new CobrarParqueo(8);
        jDesktopPane1.add(cobrarparqueo);
        cobrarparqueo.show();
                }else{
                    jfiIngresoParqueo ingresoparqueo = new jfiIngresoParqueo(8);
        // se añade al jDesktopPane
        jDesktopPane1.add(ingresoparqueo);
        //se muestra en pantalla
        ingresoparqueo.show();
                }
    }//GEN-LAST:event_Carro8MouseClicked

    private void Carro9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carro9MouseClicked
        // TODO add your handling code here:
        if (status[8]==1) {
        CobrarParqueo cobrarparqueo = new CobrarParqueo(9);
        jDesktopPane1.add(cobrarparqueo);
        cobrarparqueo.show();
                }else{
                    jfiIngresoParqueo ingresoparqueo = new jfiIngresoParqueo(9);
        // se añade al jDesktopPane
        jDesktopPane1.add(ingresoparqueo);
        //se muestra en pantalla
        ingresoparqueo.show();
                }
    }//GEN-LAST:event_Carro9MouseClicked

    private void Carro10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carro10MouseClicked
        // TODO add your handling code here:
        if (status[9]==1) {
        CobrarParqueo cobrarparqueo = new CobrarParqueo(10);
        jDesktopPane1.add(cobrarparqueo);
        cobrarparqueo.show();
                }else{
                    jfiIngresoParqueo ingresoparqueo = new jfiIngresoParqueo(10);
        // se añade al jDesktopPane
        jDesktopPane1.add(ingresoparqueo);
        //se muestra en pantalla
        ingresoparqueo.show();
                }
    }//GEN-LAST:event_Carro10MouseClicked

    private void Carro11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carro11MouseClicked
        // TODO add your handling code here:
        if (status[10]==1) {
        CobrarParqueo cobrarparqueo = new CobrarParqueo(11);
        jDesktopPane1.add(cobrarparqueo);
        cobrarparqueo.show();
                }else{
                    jfiIngresoParqueo ingresoparqueo = new jfiIngresoParqueo(11);
        // se añade al jDesktopPane
        jDesktopPane1.add(ingresoparqueo);
        //se muestra en pantalla
        ingresoparqueo.show();
                }
    }//GEN-LAST:event_Carro11MouseClicked

    private void Carro12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carro12MouseClicked
        // TODO add your handling code here:
        if (status[11]==1) {
        CobrarParqueo cobrarparqueo = new CobrarParqueo(12);
        jDesktopPane1.add(cobrarparqueo);
        cobrarparqueo.show();
                }else{
                    jfiIngresoParqueo ingresoparqueo = new jfiIngresoParqueo(12);
        // se añade al jDesktopPane
        jDesktopPane1.add(ingresoparqueo);
        //se muestra en pantalla
        ingresoparqueo.show();
                }
    }//GEN-LAST:event_Carro12MouseClicked

    private void Carro13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carro13MouseClicked
        // TODO add your handling code here:
        if (status[12]==1) {
        CobrarParqueo cobrarparqueo = new CobrarParqueo(13);
        jDesktopPane1.add(cobrarparqueo);
        cobrarparqueo.show();
                }else{
                    jfiIngresoParqueo ingresoparqueo = new jfiIngresoParqueo(13);
        // se añade al jDesktopPane
        jDesktopPane1.add(ingresoparqueo);
        //se muestra en pantalla
        ingresoparqueo.show();
                }
    }//GEN-LAST:event_Carro13MouseClicked

    private void Carro14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carro14MouseClicked
        // TODO add your handling code here:
        if (status[13]==1) {
        CobrarParqueo cobrarparqueo = new CobrarParqueo(14);
        jDesktopPane1.add(cobrarparqueo);
        cobrarparqueo.show();
                }else{
                    jfiIngresoParqueo ingresoparqueo = new jfiIngresoParqueo(14);
        // se añade al jDesktopPane
        jDesktopPane1.add(ingresoparqueo);
        //se muestra en pantalla
        ingresoparqueo.show();
                }
    }//GEN-LAST:event_Carro14MouseClicked

    private void Carro15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carro15MouseClicked
        // TODO add your handling code here:
        if (status[14]==1) {
        CobrarParqueo cobrarparqueo = new CobrarParqueo(15);
        jDesktopPane1.add(cobrarparqueo);
        cobrarparqueo.show();
                }else{
                    jfiIngresoParqueo ingresoparqueo = new jfiIngresoParqueo(15);
        // se añade al jDesktopPane
        jDesktopPane1.add(ingresoparqueo);
        //se muestra en pantalla
        ingresoparqueo.show();
                }
    }//GEN-LAST:event_Carro15MouseClicked

    private void InfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoActionPerformed
        // TODO add your handling code here:
        Info info = new Info();
        info.setVisible(true);
    }//GEN-LAST:event_InfoActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        ReporteFechas rf = new ReporteFechas();
        rf.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Carro1;
    private javax.swing.JLabel Carro10;
    private javax.swing.JLabel Carro11;
    private javax.swing.JLabel Carro12;
    private javax.swing.JLabel Carro13;
    private javax.swing.JLabel Carro14;
    private javax.swing.JLabel Carro15;
    private javax.swing.JLabel Carro2;
    private javax.swing.JLabel Carro3;
    private javax.swing.JLabel Carro4;
    private javax.swing.JLabel Carro5;
    private javax.swing.JLabel Carro6;
    private javax.swing.JLabel Carro7;
    private javax.swing.JLabel Carro8;
    private javax.swing.JLabel Carro9;
    private javax.swing.JMenuItem CobrarParqueo;
    private javax.swing.JMenu ControlParqueo;
    private javax.swing.JLabel Fondo;
    private javax.swing.JMenuItem Info;
    private javax.swing.JMenu IngresoParqueo;
    private javax.swing.JMenu Inicio;
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JMenu Salir;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem miIngresoCliente;
    // End of variables declaration//GEN-END:variables
}
